

export const DataFeature= [
 {
  id: 41,
  name: "Floral Pointelle Smoocked Crop Top",
  size: ["M", "L", "XL"],
  brand: "StyleHub",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/41-large_default/floral-pointelle-smocked-crop-top-in-whitecap.jpg",
  price: 27,
  oldPrice: 30,
  rating: 4,
  discount: -10,
  hasOffer: false,
},
{
  id: 42,
  name: "textured Top With Cuffed Sleeves",
  size: ["M", "L", "XL"],
  brand: "FashionEra",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/140-medium_default/textured-top-with-cuffed-sleeves.jpg",
  price: 18,
  oldPrice: 22,
  rating: 5,
  discount: -15,
  hasOffer: true,
},
{
  id: 43,
  name: "Peach Coloured Ruched Tie-Front Crop",
  size: ["M", "L", "XL"],
  brand: "UrbanWear",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/122-medium_default/peach-coloured-ruched-tie-front-crop-top.jpg",
  price: 35,
  oldPrice: 40,
  rating: 4,
  discount: -12,
  hasOffer: false,
},
{
  id: 44,
  name: "Women Pink Cotton Long Sleeve Crop Top",
  size: ["M", "L", "XL"],
  brand: "TrendLine",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/52-medium_default/women-pink-cotton-long-sleeve-crop-top.jpg",
  price: 45,
  oldPrice: 55,
  rating: 5,
  discount: -20,
  hasOffer: true,
},
{
  id: 45,
  name: "DressBary Women's Printed Ploy Crop Top",
  size: ["M", "L", "XL"],
  brand: "ModernFit",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/132-large_default/dressberry-women-s-printed-poly-crop-top.jpg",
  price: 60,
  oldPrice: 75,
  rating: 4,
  discount: -18,
  hasOffer: true,
},
{
  id: 46,
  name: "long Sleeve Neck Top",
  size: ["M", "L", "XL"],
  brand: "EliteStyle",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/56-medium_default/womens-self-design-long-sleeve-neck-top.jpg",
  price: 50,
  oldPrice: 65,
  rating: 5,
  discount: -25,
  hasOffer: true,
},
{
  id: 47,
  name: "Summer Shirt",
  size: ["M", "L", "XL"],
  brand: "CoolWear",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/4/7/47-home_default.jpg",
  price: 80,
  oldPrice: 95,
  rating: 4,
  discount: -15,
  hasOffer: true,
},
{
  id: 48,
  name: "Woman's Jacket",
  size: ["M", "L", "XL"],
  brand: "StyleNova",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/4/9/49-home_default.jpg",
  price: 120,
  oldPrice: 150,
  rating: 5,
  discount: -30,
  hasOffer: false,
},
{
  id: 49,
  name: "Woman's Jacket",
  size: ["M", "L", "XL"],
  brand: "WinterEdge",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/5/1/51-home_default.jpg",
  price: 90,
  oldPrice: 110,
  rating: 4,
  discount: -22,
  hasOffer: true,
},
{
  id: 50,
  name: "Women's Dress",
  size: ["M", "L", "XL"],
  brand: "ChicStyle",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/5/3/53-home_default.jpg",
  price: 70,
  oldPrice: 85,
  rating: 5,
  discount: -17,
  hasOffer: true,
},
];
