
export const DataJacket = [
  {
  id: 31,
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/1/21-home_default.jpg",
  brand: "EcoShop",
  name: "Classic Winter Wool Blazer Jacket",
  size: ["M", "L", "XL"],
  rating: 5,
  reviews: 12,
  price: 120,
  oldPrice: 150,
  discount: 20,
  hasOffer: true,
},
{
  id: 32,
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/2/22-home_default.jpg",
  brand: "EcoShop",
  name: "Slim Fit Formal Black Blazer",
  size: ["M", "L", "XL"],
  rating: 4,
  reviews: 18,
  price: 95,
  oldPrice: 110,
  discount: 15,
  hasOffer: true,
},
{
  id: 33,
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/3/23-home_default.jpg",
  brand: "EcoShop",
  name: "Premium Navy Blue Office Blazer",
  size: ["M", "L", "XL"],
  rating: 5,
  reviews: 22,
  price: 130,
  oldPrice: 145,
  discount: 10,
  hasOffer: true,
},
{
  id: 34,
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/4/24-home_default.jpg",
  brand: "EcoShop",
  name: "Casual Street Style Jacket Blazer",
  size: ["M", "L", "XL"],
  rating: 4,
  reviews: 9,
  price: 75,
  hasOffer: false,
},
{
  id: 35,
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/5/25-home_default.jpg",
  brand: "EcoShop",
  name: "Men’s Formal Wedding Blazer",
  size: ["M", "L", "XL"],
  rating: 5,
  reviews: 30,
  price: 160,
  oldPrice: 180,
  discount: 12,
  hasOffer: true,
},
{
  id: 36,
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/6/26-home_default.jpg",
  brand: "EcoShop",
  name: "Slim Fit Grey Business Blazer",
  size: ["M", "L", "XL"],
  rating: 4,
  reviews: 14,
  price: 105,
  hasOffer: false,
},
{
  id: 37,
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/7/27-home_default.jpg",
  brand: "EcoShop",
  name: "Luxury Double Button Blazer Jacket",
  size: ["M", "L", "XL"],
  rating: 5,
  reviews: 25,
  price: 140,
  oldPrice: 160,
  discount: 13,
  hasOffer: true,
},
{
  id: 38,
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/8/28-home_default.jpg",
  brand: "EcoShop",
  name: "Casual Denim Blazer Jacket Style",
  size: ["M", "L", "XL"],
  rating: 4,
  reviews: 11,
  price: 85,
  hasOffer: false,
},
{
  id: 39,
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/9/29-home_default.jpg",
  brand: "EcoShop",
  name: "Winter Thick Warm Blazer Coat",
  size: ["M", "L", "XL"],
  rating: 5,
  reviews: 19,
  price: 150,
  oldPrice: 175,
  discount: 14,
  hasOffer: true,
},
{
  id: 40,
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/3/0/30-home_default.jpg",
  brand: "EcoShop",
  name: "Modern Casual Slim Fit Blazer Jacket",
  size: ["M", "L", "XL"],
  rating: 4,
  reviews: 8,
  price: 90,
  hasOffer: false,
},
];