
export const DataSheos = [
  {
  id: 21,
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf55sB55eKaMRmtzf4RPaTxNFNmizi84CFPJg_gtafBw&s=10",
  brand: "BabyStyle",
  name: "Baby Girl Floral Cotton Dress",
  size: ["M", "L", "XL"],
  rating: 5,
  reviews: 22,
  price: 85,
  oldPrice: 100,
  discount: 15,
  hasOffer: true,
},
{
  id: 22,
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc30rWAsDBPf4iTCoYKr_z7Ju3QRgdstBYYHVYJG9b3cVH7FESR-4VHO90&s=10",
  brand: "BabyStyle",
  name: "Baby Boy Casual Romper",
  size: ["M", "L", "XL"],
  rating: 4,
  reviews: 18,
  price: 60,
  hasOffer: false,
},
{
  id: 23,
  image: "https://smartdeal.com.bd/public/uploads/all/a0lwZSQ6uLVrGvI7Zi0XvJAPyzNrJQ87gfoHaiLN.jpg",
  brand: "BabyStyle",
  name: "Premium Baby Party Dress",
  size: ["M", "L", "XL"],
  rating: 5,
  reviews: 30,
  price: 120,
  oldPrice: 140,
  discount: 14,
  hasOffer: true,
},
{
  id: 24,
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0cllgXYsnAncoUD85MEfdPXd8uorfzjU8d5flJYE4LtHQ8Pix7CfKRuU5&s=10",
  brand: "BabyStyle",
  name: "Baby Cotton Frock",
  size: ["M", "L", "XL"],
  rating: 4,
  reviews: 12,
  price: 75,
  hasOffer: false,
},
{
  id: 25,
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0x1dlt8MX5NR6gxDGcRn6zsqXefuFwhJMgVZ1W-MAUQ&s=10",
  brand: "BabyStyle",
  name: "Baby Winter Hooded Dress",
  size: ["M", "L", "XL"],
  rating: 5,
  reviews: 16,
  price: 95,
  oldPrice: 110,
  discount: 13,
  hasOffer: true,
},
{
  id: 26,
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-papvoVPsmsYPyPcGR5Jt91Wy6_kFP-1URSOWsuM7GA&s=10",
  brand: "BabyStyle",
  name: "Soft Baby Sleepsuit",
  size: ["M", "L", "XL"],
  rating: 4,
  reviews: 10,
  price: 55,
  hasOffer: false,
},
{
  id: 27,
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBdhz79Bo7FzDyvz7koEvY2PAAAzkfuGLW3NHRe3lXZg&s=10",
  brand: "BabyStyle",
  name: "Baby Princess Party Dress",
  size: ["M", "L", "XL"],
  rating: 5,
  reviews: 25,
  price: 70,
  oldPrice: 85,
  discount: 18,
  hasOffer: true,
},
{
  id: 28,
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAZbprz5Gr2BTF69eA0kIi4FxB75AhNF_8Y5ChJA3qDQ&s=10",
  brand: "BabyStyle",
  name: "Baby Summer Cotton Outfit",
  size: ["M", "L", "XL"],
  rating: 4,
  reviews: 14,
  price: 65,
  hasOffer: false,
},
{
  id: 29,
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDZ0M3EGFWjRxy3t2rVf7J9kiVmXgj06wDrOZhbNCoyg&s=10",
  brand: "BabyStyle",
  name: "Premium Baby Winter Set",
  size: ["M", "L", "XL"],
  rating: 5,
  reviews: 19,
  price: 140,
  oldPrice: 160,
  discount: 12,
  hasOffer: true,
},
{
  id: 30,
  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9tQ40VVhqoqBrmSNjCnRX5IDJK6fH4dIdc8kCaDPahg&s=10",
  brand: "BabyStyle",
  name: "Baby Everyday Dress",
  size: ["M", "L", "XL"],
  rating: 4,
  reviews: 8,
  price: 25,
  hasOffer: false,
},
];
 