

export const DataDealWeaks = [
 
  {
  id: 51,
  name: "Casual Hudi",
  size: ["M", "L", "XL"],
  brand: "EcoShop",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/3/4/34-home_default.jpg",
  price: 27,
  oldPrice: 30,
  rating: 4,
  discount: -10,
  hasOffer: true,
},
{
  id: 52,
  name: "Casual Summer T-Shirt",
  size: ["M", "L", "XL"],
  brand: "EcoShop",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/140-large_default/textured-top-with-cuffed-sleeves.jpg",
  price: 18,
  oldPrice: 22,
  rating: 5,
  discount: -15,
  hasOffer: true,
},
{
  id: 53,
  name: "Slim Fit Jacket",
  size: ["M", "L", "XL"],
  brand: "EcoShop",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/3/9/39-home_default.jpg",
  price: 35,
  oldPrice: 40,
  rating: 4,
  discount: -12,
  hasOffer: true,
},
{
  id: 54,
  name: "Classic T-shirt",
  size: ["M", "L", "XL"],
  brand: "EcoShop",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/4/1/41-home_default.jpg",
  price: 45,
  oldPrice: 55,
  rating: 5,
  discount: -20,
  hasOffer: true,
},
{
  id: 55,
  name: "Summer Shirt",
  size: ["M", "L", "XL"],
  brand: "EcoShop",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/4/3/43-home_default.jpg",
  price: 60,
  oldPrice: 75,
  rating: 4,
  discount: -18,
  hasOffer: true,
},
{
  id: 56,
  name: "Fashion Shirt",
  size: ["M", "L", "XL"],
  brand: "EcoShop",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/4/5/45-home_default.jpg",
  price: 50,
  oldPrice: 65,
  rating: 5,
  discount: -25,
  hasOffer: true,
},
{
  id: 57,
  name: "Summer Shirt",
  size: ["M", "L", "XL"],
  brand: "EcoShop",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/4/7/47-home_default.jpg",
  price: 80,
  oldPrice: 95,
  rating: 4,
  discount: -15,
  hasOffer: true,
},
{
  id: 58,
  name: "Woman's Jacket",
  size: ["M", "L", "XL"],
  brand: "EcoShop",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/4/9/49-home_default.jpg",
  price: 120,
  oldPrice: 150,
  rating: 5,
  discount: -30,
  hasOffer: true,
},
{
  id: 59,
  name: "Woman's Jacket",
  size: ["M", "L", "XL"],
  brand: "EcoShop",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/5/1/51-home_default.jpg",
  price: 90,
  oldPrice: 110,
  rating: 4,
  discount: -22,
  hasOffer: true,
},
{
  id: 60,
  name: "Women's Dress",
  size: ["M", "L", "XL"],
  brand: "EcoShop",
  image:
    "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/5/3/53-home_default.jpg",
  price: 70,
  oldPrice: 85,
  rating: 5,
  discount: -17,
  hasOffer: true,
},
];
