export type Product = {
  id: number;
  image: string;
  brand: string;
  name: string;
  category: string;
  color: string;
  size: string[];
  rating: number;
  reviews: number;
  price: number;
  oldPrice?: number;
  discount?: number;
  hasOffer: boolean;
};

export const AllProducts: Product[] = [
  {
    id: 1,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab",
    brand: "Nike",
    name: "Men Black Hoodie",
    category: "Hoodies",
    color: "black",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 120,
    price: 55,
    oldPrice: 70,
    discount: 20,
    hasOffer: true,
  },
  {
    id: 2,
    image: "https://images.unsplash.com/photo-1520975958225-5c5a8a1f8f10",
    brand: "Adidas",
    name: "White Classic T-Shirt",
    category: "T-Shirts",
    color: "white",
    size: ["S", "M", "L"],
    rating: 4,
    reviews: 80,
    price: 25,
    hasOffer: false,
  },
  {
    id: 3,
    image: "https://images.unsplash.com/photo-1521335629791-ce4aec67dd49",
    brand: "Zara",
    name: "Slim Fit Blue Jeans",
    category: "Jeans",
    color: "blue",
    size: ["M", "L"],
    rating: 5,
    reviews: 95,
    price: 60,
    oldPrice: 75,
    discount: 15,
    hasOffer: true,
  },
  {
    id: 4,
    image: "https://images.unsplash.com/photo-1520975682031-a6c4b2b0f5f6",
    brand: "H&M",
    name: "Casual Grey Hoodie",
    category: "Hoodies",
    color: "gray",
    size: ["S", "M", "L", "XL"],
    rating: 4,
    reviews: 60,
    price: 50,
    hasOffer: false,
  },
  {
    id: 5,
    image: "https://images.unsplash.com/photo-1520974735194-6d1f1d1a2b2a",
    brand: "Levi's",
    name: "Denim Jacket Classic",
    category: "Jackets",
    color: "blue",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 150,
    price: 90,
    oldPrice: 110,
    discount: 18,
    hasOffer: true,
  },

  {
    id: 6,
    image: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
    brand: "Nike",
    name: "Running Sport Shoes",
    category: "Shoes",
    color: "black",
    size: ["40", "41", "42", "43"],
    rating: 5,
    reviews: 200,
    price: 120,
    oldPrice: 150,
    discount: 20,
    hasOffer: true,
  },
  {
    id: 7,
    image: "https://images.unsplash.com/photo-1520975682031-a6c4b2b0f5f6",
    brand: "Adidas",
    name: "White Sneakers",
    category: "Shoes",
    color: "white",
    size: ["40", "41", "42"],
    rating: 4,
    reviews: 110,
    price: 85,
    hasOffer: false,
  },
  {
    id: 8,
    image: "https://images.unsplash.com/photo-1520975853936-4f3b1b2d2f6e",
    brand: "Zara",
    name: "Women Summer Dress",
    category: "Dress",
    color: "red",
    size: ["S", "M", "L"],
    rating: 5,
    reviews: 90,
    price: 45,
    oldPrice: 60,
    discount: 25,
    hasOffer: true,
  },
  {
    id: 9,
    image: "https://images.unsplash.com/photo-1520975958225-5c5a8a1f8f10",
    brand: "H&M",
    name: "Black Polo Shirt",
    category: "T-Shirts",
    color: "black",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 70,
    price: 30,
    hasOffer: false,
  },
  {
    id: 10,
    image: "https://images.unsplash.com/photo-1520974735194-6d1f1d1a2b2a",
    brand: "Nike",
    name: "Winter Jacket Premium",
    category: "Jackets",
    color: "green",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 140,
    price: 110,
    oldPrice: 140,
    discount: 22,
    hasOffer: true,
  },

  {
    id: 11,
    image: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
    brand: "Adidas",
    name: "Gym Hoodie Grey",
    category: "Hoodies",
    color: "gray",
    size: ["S", "M", "L"],
    rating: 4,
    reviews: 75,
    price: 48,
    hasOffer: false,
  },
  {
    id: 12,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab",
    brand: "Levi's",
    name: "Skinny Black Jeans",
    category: "Jeans",
    color: "black",
    size: ["M", "L"],
    rating: 5,
    reviews: 160,
    price: 70,
    oldPrice: 90,
    discount: 18,
    hasOffer: true,
  },
  {
    id: 13,
    image: "https://images.unsplash.com/photo-1520975853936-4f3b1b2d2f6e",
    brand: "Zara",
    name: "Casual White Shirt",
    category: "Shirts",
    color: "white",
    size: ["S", "M", "L"],
    rating: 4,
    reviews: 85,
    price: 35,
    hasOffer: false,
  },
  {
    id: 14,
    image: "https://images.unsplash.com/photo-1520975958225-5c5a8a1f8f10",
    brand: "H&M",
    name: "Oversized Hoodie",
    category: "Hoodies",
    color: "black",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 130,
    price: 65,
    oldPrice: 80,
    discount: 15,
    hasOffer: true,
  },
  {
    id: 15,
    image: "https://images.unsplash.com/photo-1520974735194-6d1f1d1a2b2a",
    brand: "Nike",
    name: "Street Style Jacket",
    category: "Jackets",
    color: "blue",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 190,
    price: 130,
    oldPrice: 160,
    discount: 20,
    hasOffer: true,
  },

  {
    id: 16,
    image: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
    brand: "Adidas",
    name: "Training Shoes",
    category: "Shoes",
    color: "black",
    size: ["40", "41", "42", "43"],
    rating: 4,
    reviews: 100,
    price: 95,
    hasOffer: false,
  },
  {
    id: 17,
    image: "https://images.unsplash.com/photo-1520975853936-4f3b1b2d2f6e",
    brand: "Zara",
    name: "Elegant Women Dress",
    category: "Dress",
    color: "green",
    size: ["S", "M", "L"],
    rating: 5,
    reviews: 115,
    price: 55,
    oldPrice: 70,
    discount: 18,
    hasOffer: true,
  },
  {
    id: 18,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab",
    brand: "Levi's",
    name: "Blue Denim Shirt",
    category: "Shirts",
    color: "blue",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 170,
    price: 50,
    hasOffer: false,
  },
  {
    id: 19,
    image: "https://images.unsplash.com/photo-1520975958225-5c5a8a1f8f10",
    brand: "Nike",
    name: "Fitness T-Shirt",
    category: "T-Shirts",
    color: "red",
    size: ["S", "M", "L"],
    rating: 4,
    reviews: 60,
    price: 28,
    hasOffer: false,
  },
  {
    id: 20,
    image: "https://images.unsplash.com/photo-1520975682031-a6c4b2b0f5f6",
    brand: "H&M",
    name: "Winter Coat Premium",
    category: "Jackets",
    color: "black",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 210,
    price: 140,
    oldPrice: 180,
    discount: 25,
    hasOffer: true,
  },
  
];