export const totalProducts = [
  {
    id: 1,
    slug: "benetton-regular-fit-sweatshirt",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/1/5/15-home_default.jpg",
    brand: "Top-10",
    name: "Benetton Regular Fit Sweatshirt",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 5,
    price: 47.5,
    oldPrice: 50,
    discount: 5,
    hasOffer: true,
    description: "A cozy and classic regular fit sweatshirt perfect for layering on casual chilly days.",
  },
  {
    id: 2,
    slug: "premium-cotton-hoodie",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/1/6/16-home_default.jpg",
    brand: "EcoShop",
    name: "Premium Cotton Hoodie",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 8,
    price: 65,
    hasOffer: false,
    description: "Crafted from ultra-soft premium organic cotton, offering ultimate everyday comfort.",
  },
  {
    id: 3,
    slug: "slim-fit-denim-jacket",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/1/7/17-home_default.jpg",
    brand: "JARA",
    name: "Slim Fit Denim Jacket",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 12,
    price: 80,
    oldPrice: 90,
    discount: 10,
    hasOffer: true,
    description: "A timeless slim fit denim jacket featuring a classic wash and heavy-duty stitching.",
  },
  {
    id: 4,
    slug: "classic-white-shirt",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/1/8/18-home_default.jpg",
    brand: "EcoShop",
    name: "Classic White Shirt",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 20,
    price: 35,
    hasOffer: false,
    description: "Crisp and lightweight smart casual shirt, a versatile staple for any modern wardrobe.",
  },
  {
    id: 5,
    slug: "summer-t-shirt-premium",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/1/9/19-home_default.jpg",
    brand: "Ferrari",
    name: "Summer T-Shirt Premium",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 7,
    price: 25,
    oldPrice: 30,
    discount: 15,
    hasOffer: true,
    description: "Breathable and stylish premium cotton tee designed to keep you cool all summer long.",
  },
  {
    id: 6,
    slug: "casual-black-hoodie",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/0/20-home_default.jpg",
    brand: "EcoShop",
    name: "Casual Black Hoodie",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 10,
    price: 55,
    hasOffer: false,
    description: "The ultimate casual black hoodie featuring a spacious kangaroo pocket and adjustable drawstrings.",
  },
  {
    id: 7,
    slug: "stylish-winter-coat",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/1/21-home_default.jpg",
    brand: "EcoShop",
    name: "Stylish Winter Coat",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 14,
    price: 120,
    oldPrice: 150,
    discount: 20,
    hasOffer: true,
    description: "An elegant, well-insulated long coat built to withstand sub-zero temperatures in style.",
  },
  {
    id: 8,
    slug: "sport-jacket",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/2/22-home_default.jpg",
    brand: "EcoShop",
    name: "Sport Jacket",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 9,
    price: 70,
    hasOffer: false,
    description: "Lightweight, wind-resistant athletic jacket ideal for workouts or outdoor adventures.",
  },
  {
    id: 9,
    slug: "premium-hoodie-grey",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/3/23-home_default.jpg",
    brand: "EcoShop",
    name: "Premium Hoodie Grey",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 18,
    price: 60,
    oldPrice: 68,
    discount: 12,
    hasOffer: true,
    description: "A minimalist grey hoodie crafted with heavy fleece for a premium structured look and feel.",
  },
  {
    id: 10,
    slug: "casual-streetwear-tee",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/4/24-home_default.jpg",
    brand: "EcoShop",
    name: "Casual Streetwear Tee",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 11,
    price: 28,
    hasOffer: false,
    description: "An urban-inspired streetwear t-shirt featuring a relaxed, dropped-shoulder aesthetic.",
  },
  {
    id: 11,
    slug: "winter-fashion-hoodie",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/5/25-home_default.jpg",
    brand: "EcoShop",
    name: "Winter Fashion Hoodie",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 13,
    price: 72,
    oldPrice: 80,
    discount: 10,
    hasOffer: true,
    description: "Thick-lined fashionable winter hoodie engineered to lock in heat without looking bulky.",
  },
  {
    id: 12,
    slug: "premium-casual-jacket",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/6/26-home_default.jpg",
    brand: "EcoShop",
    name: "Premium Casual Jacket",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 9,
    price: 85,
    hasOffer: false,
    description: "A sleek, transitional jacket that effortlessly elevates your smart-casual look.",
  },
  {
    id: 13,
    slug: "oversized-sweatshirt",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/7/27-home_default.jpg",
    brand: "EcoShop",
    name: "Oversized Sweatshirt",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 15,
    price: 58,
    oldPrice: 65,
    discount: 8,
    hasOffer: true,
    description: "A trend-forward oversized sweatshirt designed for maximum lounging comfort.",
  },
  {
    id: 14,
    slug: "modern-street-jacket",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/8/28-home_default.jpg",
    brand: "EcoShop",
    name: "Modern Street Jacket",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 6,
    price: 95,
    hasOffer: false,
    description: "Bold contemporary design elements make this street jacket stand out in any crowd.",
  },
  {
    id: 15,
    slug: "mens-denim-shirt",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/9/29-home_default.jpg",
    brand: "EcoShop",
    name: "Men's Denim Shirt",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 21,
    price: 42,
    oldPrice: 50,
    discount: 15,
    hasOffer: true,
    description: "A rugged yet tailored denim shirt featuring durable button snaps and dual chest pockets.",
  },
  {
    id: 16,
    slug: "warm-winter-hoodie",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/3/0/30-home_default.jpg",
    brand: "EcoShop",
    name: "Warm Winter Hoodie",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 10,
    price: 62,
    hasOffer: false,
    description: "Features soft brushed fleece on the inside to keep you extra warm during frosty morning walks.",
  },
  {
    id: 17,
    slug: "luxury-cotton-t-shirt",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/3/1/31-home_default.jpg",
    brand: "EcoShop",
    name: "Luxury Cotton T-Shirt",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 17,
    price: 33,
    oldPrice: 40,
    discount: 18,
    hasOffer: true,
    description: "An exceptionally soft, high-thread-count cotton t-shirt with a premium tailored finish.",
  },
  {
    id: 18,
    slug: "urban-style-coat",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/3/2/32-home_default.jpg",
    brand: "EcoShop",
    name: "Urban Style Coat",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 19,
    price: 140,
    oldPrice: 170,
    discount: 20,
    hasOffer: true,
    description: "Sleek and professional urban overcoat tailored to blend beautifully into city life.",
  },
  {
    id: 19,
    slug: "classic-polo-t-shirt",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/3/3/33-home_default.jpg",
    brand: "EcoShop",
    name: "Classic Polo T-Shirt",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 7,
    price: 38,
    hasOffer: false,
    description: "A timeless smart-casual polo shirt made from textured pique cotton with tipped collar accents.",
  },
  {
    id: 20,
    slug: "fashionable-sports-hoodie",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/3/4/34-home_default.jpg",
    brand: "EcoShop",
    name: "Fashionable Sports Hoodie",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 16,
    price: 68,
    oldPrice: 75,
    discount: 9,
    hasOffer: true,
    description: "Athletic-fit hoodie with moisture-wicking technology and a modern geometric silhouette.",
  },
  {
    id: 21,
    slug: "baby-girl-floral-cotton-dress",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf55sB55eKaMRmtzf4RPaTxNFNmizi84CFPJg_gtafBw&s=10",
    brand: "BabyStyle",
    name: "Baby Girl Floral Cotton Dress",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 22,
    price: 85,
    oldPrice: 100,
    discount: 15,
    hasOffer: true,
    description: "An adorable, highly breathable pure cotton dress adorned with a vibrant spring floral print.",
  },
  {
    id: 22,
    slug: "baby-boy-casual-romper",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc30rWAsDBPf4iTCoYKr_z7Ju3QRgdstBYYHVYJG9b3cVH7FESR-4VHO90&s=10",
    brand: "BabyStyle",
    name: "Baby Boy Casual Romper",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 18,
    price: 60,
    hasOffer: false,
    description: "Easy snap-button romper made of baby-safe fabric, optimized for quick diaper changes.",
  },
  {
    id: 23,
    slug: "premium-baby-party-dress",
    image: "https://smartdeal.com.bd/public/uploads/all/a0lwZSQ6uLVrGvI7Zi0XvJAPyzNrJQ87gfoHaiLN.jpg",
    brand: "BabyStyle",
    name: "Premium Baby Party Dress",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 30,
    price: 120,
    oldPrice: 140,
    discount: 14,
    hasOffer: true,
    description: "An elegant tulle dress embedded with delicate lace accents for extra special celebrations.",
  },
  {
    id: 24,
    slug: "baby-cotton-frock",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0cllgXYsnAncoUD85MEfdPXd8uorfzjU8d5flJYE4LtHQ8Pix7CfKRuU5&s=10",
    brand: "BabyStyle",
    name: "Baby Cotton Frock",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 12,
    price: 75,
    hasOffer: false,
    description: "A super soft everyday frock designed with a flared skirt for maximum play-time comfort.",
  },
  {
    id: 25,
    slug: "baby-winter-hooded-dress",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0x1dlt8MX5NR6gxDGcRn6zsqXefuFwhJMgVZ1W-MAUQ&s=10",
    brand: "BabyStyle",
    name: "Baby Winter Hooded Dress",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 16,
    price: 95,
    oldPrice: 110,
    discount: 13,
    hasOffer: true,
    description: "Plush fleece-lined winter dress topped with an adorable bear-eared hood to keep baby warm.",
  },
  {
    id: 26,
    slug: "soft-baby-sleepsuit",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-papvoVPsmsYPyPcGR5Jt91Wy6_kFP-1URSOWsuM7GA&s=10",
    brand: "BabyStyle",
    name: "Soft Baby Sleepsuit",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 10,
    price: 55,
    hasOffer: false,
    description: "Ultra-comfy closed-toe sleepsuit crafted from hypoallergenic fabrics for a peaceful night's rest.",
  },
  {
    id: 27,
    slug: "baby-princess-party-dress",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBdhz79Bo7FzDyvz7koEvY2PAAAzkfuGLW3NHRe3lXZg&s=10",
    brand: "BabyStyle",
    name: "Baby Princess Party Dress",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 25,
    price: 70,
    oldPrice: 85,
    discount: 18,
    hasOffer: true,
    description: "A charming princess-cut dress outfitted with a satin waistband and multi-layered tulle flare.",
  },
  {
    id: 28,
    slug: "baby-summer-cotton-outfit",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAZbprz5Gr2BTF69eA0kIi4FxB75AhNF_8Y5ChJA3qDQ&s=10",
    brand: "BabyStyle",
    name: "Baby Summer Cotton Outfit",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 14,
    price: 65,
    hasOffer: false,
    description: "Light, airy, and gentle matching cotton set perfect for hot summer afternoons outdoors.",
  },
  {
    id: 29,
    slug: "premium-baby-winter-set",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDZ0M3EGFWjRxy3t2rVf7J9kiVmXgj06wDrOZhbNCoyg&s=10",
    brand: "BabyStyle",
    name: "Premium Baby Winter Set",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 19,
    price: 140,
    oldPrice: 160,
    discount: 12,
    hasOffer: true,
    description: "A complete multi-piece insulated knitwear set designed to lock in warmth on chilly days.",
  },
  {
    id: 30,
    slug: "baby-everyday-dress",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9tQ40VVhqoqBrmSNjCnRX5IDJK6fH4dIdc8kCaDPahg&s=10",
    brand: "BabyStyle",
    name: "Baby Everyday Dress",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 8,
    price: 25,
    hasOffer: false,
    description: "Durable, easy-to-wash simple cotton dress optimized for daily baby exploration and play.",
  },
  {
    id: 31,
    slug: "classic-winter-wool-blazer-jacket",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/1/21-home_default.jpg",
    brand: "EcoShop",
    name: "Classic Winter Wool Blazer Jacket",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 12,
    price: 120,
    oldPrice: 150,
    discount: 20,
    hasOffer: true,
    description: "A sophisticated structured wool blazer that balances seasonal warmth with formal styling.",
  },
  {
    id: 32,
    slug: "slim-fit-formal-black-blazer",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/2/22-home_default.jpg",
    brand: "EcoShop",
    name: "Slim Fit Formal Black Blazer",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 18,
    price: 95,
    oldPrice: 110,
    discount: 15,
    hasOffer: true,
    description: "A sharp, classic formal black blazer featuring clean lines and a premium tailored taper.",
  },
  {
    id: 33,
    slug: "premium-navy-blue-office-blazer",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/3/23-home_default.jpg",
    brand: "EcoShop",
    name: "Premium Navy Blue Office Blazer",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 22,
    price: 130,
    oldPrice: 145,
    discount: 10,
    hasOffer: true,
    description: "The quintessential deep navy blue blazer, built to command attention in corporate boardrooms.",
  },
  {
    id: 34,
    slug: "casual-street-style-jacket-blazer",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/4/24-home_default.jpg",
    brand: "EcoShop",
    name: "Casual Street Style Jacket Blazer",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 9,
    price: 75,
    hasOffer: false,
    description: "An unstructured blazer jacket tailored for an effortlessly smart streetwear look.",
  },
  {
    id: 35,
    slug: "mens-formal-wedding-blazer",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/5/25-home_default.jpg",
    brand: "EcoShop",
    name: "Men’s Formal Wedding Blazer",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 30,
    price: 160,
    oldPrice: 180,
    discount: 12,
    hasOffer: true,
    description: "An exquisite luxury blazer complete with premium fabric finishes, ideal for celebrations.",
  },
  {
    id: 36,
    slug: "slim-fit-grey-business-blazer",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/6/26-home_default.jpg",
    brand: "EcoShop",
    name: "Slim Fit Grey Business Blazer",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 14,
    price: 105,
    hasOffer: false,
    description: "A versatile textured grey business blazer designed for a modern professional profile.",
  },
  {
    id: 37,
    slug: "luxury-double-button-blazer-jacket",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/7/27-home_default.jpg",
    brand: "EcoShop",
    name: "Luxury Double Button Blazer Jacket",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 25,
    price: 140,
    oldPrice: 160,
    discount: 13,
    hasOffer: true,
    description: "A premium double-breasted jacket adding vintage charm and structure to your outfit.",
  },
  {
    id: 38,
    slug: "casual-denim-blazer-jacket-style",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/8/28-home_default.jpg",
    brand: "EcoShop",
    name: "Casual Denim Blazer Jacket Style",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 11,
    price: 85,
    hasOffer: false,
    description: "Blends the casual texture of washed denim with the traditional tailored frame of a blazer.",
  },
  {
    id: 39,
    slug: "winter-thick-warm-blazer-coat",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/2/9/29-home_default.jpg",
    brand: "EcoShop",
    name: "Winter Thick Warm Blazer Coat",
    size: ["M", "L", "XL"],
    rating: 5,
    reviews: 19,
    price: 150,
    oldPrice: 175,
    discount: 14,
    hasOffer: true,
    description: "An heavily lined hybrid blazer coat designed to keep you warm through intense winter cold.",
  },
  {
    id: 40,
    slug: "modern-casual-slim-fit-blazer-jacket",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/3/0/30-home_default.jpg",
    brand: "EcoShop",
    name: "Modern Casual Slim Fit Blazer Jacket",
    size: ["M", "L", "XL"],
    rating: 4,
    reviews: 8,
    price: 90,
    hasOffer: false,
    description: "The perfect smart-casual balance; works flawlessly with both jeans and tailored trousers.",
  },
  {
    id: 41,
    slug: "floral-pointelle-smocked-crop-top",
    name: "Floral Pointelle Smoocked Crop Top",
    size: ["M", "L", "XL"],
    brand: "StyleHub",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/41-large_default/floral-pointelle-smocked-crop-top-in-whitecap.jpg",
    price: 27,
    oldPrice: 30,
    rating: 4,
    discount: -10,
    hasOffer: false,
    description: "A trendy smocked crop top showcasing a delicate floral pointelle texture for summer vibes.",
  },
  {
    id: 42,
    slug: "textured-top-with-cuffed-sleeves",
    name: "textured Top With Cuffed Sleeves",
    size: ["M", "L", "XL"],
    brand: "FashionEra",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/140-medium_default/textured-top-with-cuffed-sleeves.jpg",
    price: 18,
    oldPrice: 22,
    rating: 5,
    discount: -15,
    hasOffer: true,
    description: "Features elegant crinkle-textured fabric paired beautifully with crisp, pre-folded cuffed sleeves.",
  },
  {
    id: 43,
    slug: "peach-coloured-ruched-tie-front-crop",
    name: "Peach Coloured Ruched Tie-Front Crop",
    size: ["M", "L", "XL"],
    brand: "UrbanWear",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/122-medium_default/peach-coloured-ruched-tie-front-crop-top.jpg",
    price: 35,
    oldPrice: 40,
    rating: 4,
    discount: -12,
    hasOffer: false,
    description: "A playful peach-toned cropped top with adjustable center ruching and a dainty tie-front.",
  },
  {
    id: 44,
    slug: "women-pink-cotton-long-sleeve-crop-top",
    name: "Women Pink Cotton Long Sleeve Crop Top",
    size: ["M", "L", "XL"],
    brand: "TrendLine",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/52-medium_default/women-pink-cotton-long-sleeve-crop-top.jpg",
    price: 45,
    oldPrice: 55,
    rating: 5,
    discount: -20,
    hasOffer: true,
    description: "Breathable pink cotton long sleeve crop top designed for easygoing, fashionable everyday wear.",
  },
  {
    id: 45,
    slug: "dressbary-womens-printed-ploy-crop-top",
    name: "DressBary Women's Printed Ploy Crop Top",
    size: ["M", "L", "XL"],
    brand: "ModernFit",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/132-large_default/dressberry-women-s-printed-poly-crop-top.jpg",
    price: 60,
    oldPrice: 75,
    rating: 4,
    discount: -18,
    hasOffer: true,
    description: "A silky-smooth poly-blend crop top highlighting an artistic all-over contemporary print.",
  },
  {
    id: 46,
    slug: "long-sleeve-neck-top",
    name: "long Sleeve Neck Top",
    size: ["M", "L", "XL"],
    brand: "EliteStyle",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/56-medium_default/womens-self-design-long-sleeve-neck-top.jpg",
    price: 50,
    oldPrice: 65,
    rating: 5,
    discount: -25,
    hasOffer: true,
    description: "An elegant self-designed long sleeve top offering a flattering neckline and sophisticated profile.",
  },
  {
    id: 47,
    slug: "summer-shirt",
    name: "Summer Shirt",
    size: ["M", "L", "XL"],
    brand: "CoolWear",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/4/7/47-home_default.jpg",
    price: 80,
    oldPrice: 95,
    rating: 4,
    discount: -15,
    hasOffer: true,
    description: "Lightweight and flowy summer shirt crafted specifically to maximize breeze and comfort.",
  },
  {
    id: 48,
    slug: "womans-jacket",
    name: "Woman's Jacket",
    size: ["M", "L", "XL"],
    brand: "StyleNova",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/4/9/49-home_default.jpg",
    price: 120,
    oldPrice: 150,
    rating: 5,
    discount: -30,
    hasOffer: false,
    description: "A tailored chic outerwear option to instantly upgrade a basic t-shirt and jeans look.",
  },
  {
    id: 49,
    slug: "womans-jacket-winter-edge",
    name: "Woman's Jacket",
    size: ["M", "L", "XL"],
    brand: "WinterEdge",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/5/1/51-home_default.jpg",
    price: 90,
    oldPrice: 110,
    rating: 4,
    discount: -22,
    hasOffer: true,
    description: "Insulated and durable winter jacket designed to effortlessly shield you from chilly winds.",
  },
  {
    id: 50,
    slug: "womens-dress",
    name: "Women's Dress",
    size: ["M", "L", "XL"],
    brand: "ChicStyle",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/5/3/53-home_default.jpg",
    price: 70,
    oldPrice: 85,
    rating: 5,
    discount: -17,
    hasOffer: true,
    description: "A stunningly draped dress that goes effortlessly from daytime events to evening dinners.",
  },
  {
    id: 51,
    slug: "casual-hudi",
    name: "Casual Hudi",
    size: ["M", "L", "XL"],
    brand: "EcoShop",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/3/4/34-home_default.jpg",
    price: 27,
    oldPrice: 30,
    rating: 4,
    discount: -10,
    hasOffer: true,
    description: "A laidback daily hoodie built with sustainably sourced fabrics and an ultra-soft inner lining.",
  },
  {
    id: 52,
    slug: "casual-summer-t-shirt",
    name: "Casual Summer T-Shirt",
    size: ["M", "L", "XL"],
    brand: "EcoShop",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/140-large_default/textured-top-with-cuffed-sleeves.jpg",
    price: 18,
    oldPrice: 22,
    rating: 5,
    discount: -15,
    hasOffer: true,
    description: "An incredibly lightweight, daily wear t-shirt that keeps you feeling breezy all day long.",
  },
  {
    id: 53,
    slug: "slim-fit-jacket",
    name: "Slim Fit Jacket",
    size: ["M", "L", "XL"],
    brand: "EcoShop",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/3/9/39-home_default.jpg",
    price: 35,
    oldPrice: 40,
    rating: 4,
    discount: -12,
    hasOffer: true,
    description: "A sharp slim-fitting lightweight outerwear layer perfect for transitioning between seasons.",
  },
  {
    id: 54,
    slug: "classic-t-shirt",
    name: "Classic T-shirt",
    size: ["M", "L", "XL"],
    brand: "EcoShop",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/4/1/41-home_default.jpg",
    price: 45,
    oldPrice: 55,
    rating: 5,
    discount: -20,
    hasOffer: true,
    description: "A timeless, heavy-knit cotton crew neck t-shirt designed to retain shape wash after wash.",
  },
  {
    id: 55,
    slug: "summer-shirt-ecoshop-linen",
    name: "Summer Shirt",
    size: ["M", "L", "XL"],
    brand: "EcoShop",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/4/3/43-home_default.jpg",
    price: 60,
    oldPrice: 75,
    rating: 4,
    discount: -18,
    hasOffer: true,
    description: "A relaxed linen-blend button-up shirt curated for beach days or backyard weekend gatherings.",
  },
  {
    id: 56,
    slug: "fashion-shirt",
    name: "Fashion Shirt",
    size: ["M", "L", "XL"],
    brand: "EcoShop",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/4/5/45-home_default.jpg",
    price: 50,
    oldPrice: 65,
    rating: 5,
    discount: -25,
    hasOffer: true,
    description: "A sharp button-down shirt featuring a refined modern pattern to spice up your regular rotations.",
  },
  {
    id: 57,
    slug: "summer-shirt-ecoshop-cotton",
    name: "Summer Shirt",
    size: ["M", "L", "XL"],
    brand: "EcoShop",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/4/7/47-home_default.jpg",
    price: 80,
    oldPrice: 95,
    rating: 4,
    discount: -15,
    hasOffer: true,
    description: "Breathable cotton vacation shirt engineered to stay cool and comfortable in tropical heat.",
  },
  {
    id: 58,
    slug: "womans-jacket-ecoshop-premium",
    name: "Woman's Jacket",
    size: ["M", "L", "XL"],
    brand: "EcoShop",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/4/9/49-home_default.jpg",
    price: 120,
    oldPrice: 150,
    rating: 5,
    discount: -30,
    hasOffer: true,
    description: "Premium insulated outerwear layer combining chic minimalist aesthetics with heavy utility.",
  },
  {
    id: 59,
    slug: "womans-jacket-ecoshop-winter",
    name: "Woman's Jacket",
    size: ["M", "L", "XL"],
    brand: "EcoShop",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/5/1/51-home_default.jpg",
    price: 90,
    oldPrice: 110,
    rating: 4,
    discount: -22,
    hasOffer: true,
    description: "Wind-breaking cozy outerwear coat built specifically to comfortably resist chilly weather layers.",
  },
  {
    id: 60,
    slug: "womens-dress-ecoshop",
    name: "Women's Dress",
    size: ["M", "L", "XL"],
    brand: "EcoShop",
    image: "https://prestashop.codezeel.com/PRS05/PRS050101/default/img/p/5/3/53-home_default.jpg",
    price: 70,
    oldPrice: 85,
    rating: 5,
    discount: -17,
    hasOffer: true,
    description: "An elegant casual dress boasting a flattering silhouette and an eco-friendly fabric base.",
  }
];